import { z } from "zod";

import { MediaKind } from "../enums";

// Where the uploaded asset will live in the product surface. Drives the
// storage key prefix and public URL path.
export const MediaPurpose = z.enum(["AVATAR", "COVER", "POST_MEDIA", "RECEIPT"]);
export type MediaPurpose = z.infer<typeof MediaPurpose>;

// ──────────────────────────────────────────────────────────────────────────
// Presign request / response
// ──────────────────────────────────────────────────────────────────────────

// Client calls POST /media/presign with intended metadata; server returns
// a short-lived direct-to-R2 upload URL.
export const PresignUploadBody = z.object({
  purpose: MediaPurpose,
  kind: z.nativeEnum(MediaKind),
  mimeType: z
    .string()
    .regex(/^[\w.+-]+\/[\w.+-]+$/, { message: "INVALID_MIME" })
    .max(100),
  // Client-declared size guardrail. Server enforces hard caps by MIME family.
  sizeBytes: z
    .number()
    .int()
    .positive()
    .max(100 * 1024 * 1024), // 100 MB ceiling for video/mp4
  // Optional filename hint — used only to preserve extension in the key.
  filename: z.string().max(255).optional(),
});
export type PresignUploadBody = z.infer<typeof PresignUploadBody>;

export const PresignedUpload = z.object({
  // PUT this URL with the raw bytes + required headers.
  uploadUrl: z.string().url(),
  // Public, cacheable URL once the upload completes (safe to persist to DB).
  publicUrl: z.string().url(),
  // Object key inside the bucket — handy for debugging / admin tooling.
  key: z.string(),
  // Headers the client MUST include on the PUT. Content-Type is always here.
  headers: z.record(z.string(), z.string()),
  // ISO timestamp past which the uploadUrl stops working.
  expiresAt: z.string().datetime(),
  // Compact placeholder generated by the API so clients can show a stable
  // blurred preview while the real image is loading.
  blurhash: z.string().min(6).nullable(),
});
export type PresignedUpload = z.infer<typeof PresignedUpload>;

export const MediaScanRequest = z.object({
  key: z.string().min(1).max(1024),
  publicUrl: z.string().url(),
  kind: z.nativeEnum(MediaKind),
  mimeType: z
    .string()
    .regex(/^[\w.+-]+\/[\w.+-]+$/, { message: "INVALID_MIME" })
    .max(100),
});
export type MediaScanRequest = z.infer<typeof MediaScanRequest>;

export const MediaScanStatus = z.enum(["READY", "BLOCKED", "REVIEW_REQUIRED", "SKIPPED"]);
export type MediaScanStatus = z.infer<typeof MediaScanStatus>;

export const MediaScannerResult = z.object({
  status: z.enum(["clean", "blocked", "skipped", "error"]),
  reason: z.string().optional(),
});
export type MediaScannerResult = z.infer<typeof MediaScannerResult>;

export const MediaScanResult = z.object({
  key: z.string(),
  status: MediaScanStatus,
  reasons: z.array(z.string()),
  scanners: z.record(z.string(), MediaScannerResult),
});
export type MediaScanResult = z.infer<typeof MediaScanResult>;

// ── Resumable (multipart) upload ───────────────────────────────────────────
//
// A 2 MB photo on 2G is about nine minutes. A drop at minute eight loses all
// of it, and on a connection that drops routinely that is not an edge case.
//
// R2 follows S3's multipart semantics, which means every part except the last
// must be at least 5 MiB. §15.6 asks for 256 KB parts; R2 rejects a complete
// built from those with EntityTooSmall, so the part size below is the smallest
// one that exists. See GAP-06: this makes video genuinely resumable and leaves
// a 2 MB photo as a single part.
export const MULTIPART_PART_BYTES = 5 * 1024 * 1024;

/** Below this an upload is one PUT — multipart would add two round trips. */
export const MULTIPART_MIN_BYTES = MULTIPART_PART_BYTES;

export const StartMultipartUploadBody = PresignUploadBody;
export type StartMultipartUploadBody = z.infer<typeof StartMultipartUploadBody>;

export const MultipartUpload = z.object({
  uploadId: z.string(),
  key: z.string(),
  /** Public URL once every part is committed. */
  publicUrl: z.string().url(),
  /** Bytes per part; the last part may be smaller. */
  partBytes: z.number().int().positive(),
  partCount: z.number().int().positive(),
  blurhash: z.string().min(6).nullable(),
});
export type MultipartUpload = z.infer<typeof MultipartUpload>;

export const SignMultipartPartBody = z.object({
  key: z.string().min(1).max(400),
  /** 1-based, as S3 numbers them. */
  partNumber: z.number().int().min(1).max(10_000),
});
export type SignMultipartPartBody = z.infer<typeof SignMultipartPartBody>;

export const SignedMultipartPart = z.object({
  uploadUrl: z.string().url(),
  partNumber: z.number().int().min(1),
  expiresAt: z.string().datetime(),
});
export type SignedMultipartPart = z.infer<typeof SignedMultipartPart>;

export const CompleteMultipartUploadBody = z.object({
  key: z.string().min(1).max(400),
  parts: z
    .array(z.object({ partNumber: z.number().int().min(1), etag: z.string().min(1).max(200) }))
    .min(1)
    .max(10_000),
});
export type CompleteMultipartUploadBody = z.infer<typeof CompleteMultipartUploadBody>;

export const CompletedUpload = z.object({ publicUrl: z.string().url() });
export type CompletedUpload = z.infer<typeof CompletedUpload>;
