export const HIDDEN_APP_TAB_ROUTES = [
  "activity",
  "composer",
  "company/[slug]",
  "employer/[slug]/billing",
  "employer/[slug]/[jobId]",
  "employer/[slug]/index",
  "employer/[slug]/jobs/new",
  "employer/index",
  "employer/new",
  "in/[handle]",
  "jobs/[id]",
  "jobs/index",
  "me/connections",
  "me/edit",
  "me/karama/index",
  "me/premium/index",
  "messages/new",
  "saved",
  "search",
  "settings/account",
  "settings/appearance",
  "settings/blocked",
  "settings/index",
  "settings/notifications",
  "settings/privacy",
  "settings/security",
  "settings/verification",
] as const;

export const HIDDEN_FULL_SCREEN_APP_TAB_ROUTES = ["onboarding", "messages/[roomId]"] as const;
